services:
  server:
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    container_name: farmnode_servidor
    # Usa a rede local da sua máquina (Linux) para enxergar os IPs 127.x.x.x
    network_mode: "host" 

  client:
    build:
      context: .
      dockerfile: cmd/client/Dockerfile
    container_name: farmnode_cliente
    depends_on:
      - server
    # O cliente também precisa estar na mesma rede host para abrir as portas nos IPs únicos
    network_mode: "host"